const express= require('express')
const UserRoute = express.Router()
const {createUser,LoginUser,protected,verifyUser,updatepassword,forgotpassword,resetpassword,uploadProfile,deleteuser,updateMe,logout} = require('../controllers/UserController')
const {upload} = require('../middleware/multer')
    UserRoute.route('/signup').post(createUser)
UserRoute.route('/login').post(LoginUser)
UserRoute.route('/verify').get(protected,verifyUser)
UserRoute.route('/updatepassword').patch(protected,updatepassword)
UserRoute.route('/forgotpassword').patch(forgotpassword)
UserRoute.route('/resetpassword/:resettoken').patch(resetpassword)
UserRoute.route('/photoupload').post(protected,upload,uploadProfile)
UserRoute.route('/deleteuser').delete(protected,deleteuser)
UserRoute.route('/logout').get(protected,logout)
UserRoute.route('/updateMe').patch(protected,updateMe)
module.exports = UserRoute